# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Person.create(nombres: 'anthony', apellidos: 'Herrera', fecha_nac: '16/05/1993', plan: 'basico', ciudad: 'Guayaquil', pais: 'Ecuador', usuario: 'Anth', password: '123')
Person.create(nombres: 'Gabriel', apellidos: 'Del Pino', fecha_nac: '14/07/1994', plan: 'basico', ciudad: 'Guayaquil', pais: 'Ecuador', usuario: 'crack', password: '123')
Person.create(nombres: 'Juan Jose', apellidos: 'Flores', fecha_nac: '11/08/1995', plan: 'basico', ciudad: 'Guayaquil', pais: 'Ecuador', usuario: 'jjf', password: '123')
Person.create(nombres: 'Juan', apellidos: 'Laso', fecha_nac: '18/05/1995', plan: 'basico', ciudad: 'Guayaquil', pais: 'Ecuador', usuario: 'jlaso', password: '123')

Movie.create(titulo: 'Unbroken', director: ' ', reparto: ' ', plan: 'basico', calificacion: 4)
Movie.create(titulo: 'Predator', director: ' ', reparto: ' ', plan: 'basico', calificacion: 3)
Movie.create(titulo: 'Resident Evil', director: ' ', reparto: ' ', plan: 'basico', calificacion: 2)
Movie.create(titulo: 'Rampage', director: ' ', reparto: ' ', plan: 'basico', calificacion: 4)
Movie.create(titulo: 'A quiet Place', director: ' ', reparto: ' ', plan: 'basico', calificacion: 5)
Movie.create(titulo: 'Split', director: ' ', reparto: ' ', plan: 'basico', calificacion: 5)
Movie.create(titulo: 'Dark Minds', director: ' ', reparto: ' ', plan: 'basico', calificacion: 3)
Movie.create(titulo: 'Duro de matar', director: ' ', reparto: ' ', plan: 'basico', calificacion: 3)
Movie.create(titulo: 'Gremlims', director: ' ', reparto: ' ', plan: 'basico', calificacion: 3)
Movie.create(titulo: 'Critters', director: ' ', reparto: ' ', plan: 'basico', calificacion: 3)
Movie.create(titulo: 'Leprechaun', director: ' ', reparto: ' ', plan: 'basico', calificacion: 3)
Movie.create(titulo: 'Pinocho', director: ' ', reparto: ' ', plan: 'basico', calificacion: 4)
Movie.create(titulo: 'Need for Speed', director: ' ', reparto: ' ', plan: 'basico', calificacion: 2)
Movie.create(titulo: 'Fast and Furious', director: ' ', reparto: ' ', plan: 'basico', calificacion: 2)
Movie.create(titulo: 'Detective Pikachu', director: ' ', reparto: ' ', plan: 'basico', calificacion: 4)
Movie.create(titulo: 'Dragon Ball Super: Broly', director: ' ', reparto: ' ', plan: 'basico', calificacion: 5)

Top.create(person_id: 1, movie_id: 1)
Top.create(person_id: 2, movie_id: 2)
Top.create(person_id: 3, movie_id: 1)
Top.create(person_id: 4, movie_id: 1)
Top.create(person_id: 1, movie_id: 3)
Top.create(person_id: 2, movie_id: 3)
Top.create(person_id: 3, movie_id: 4)
Top.create(person_id: 4, movie_id: 5)
Top.create(person_id: 1, movie_id: 5)
Top.create(person_id: 2, movie_id: 1)
Top.create(person_id: 3, movie_id: 6)
Top.create(person_id: 4, movie_id: 3)
Top.create(person_id: 1, movie_id: 7)
Top.create(person_id: 2, movie_id: 7)
Top.create(person_id: 3, movie_id: 7)
Top.create(person_id: 4, movie_id: 4)
Top.create(person_id: 1, movie_id: 8)
Top.create(person_id: 2, movie_id: 9)
Top.create(person_id: 3, movie_id: 10)
Top.create(person_id: 4, movie_id: 11)
Top.create(person_id: 1, movie_id: 12)
Top.create(person_id: 2, movie_id: 13)
Top.create(person_id: 3, movie_id: 14)
Top.create(person_id: 4, movie_id: 15)
Top.create(person_id: 1, movie_id: 16)
Top.create(person_id: 2, movie_id: 16)
Top.create(person_id: 3, movie_id: 16)
Top.create(person_id: 4, movie_id: 16)

